### ISSUE TITLE
Support workspace

### ISSUE THREAD

**Issue by sakurayang** [rust-build/rust-build.action#32]
here's my `Cargo.toml` on the root folder

```toml
[workspace]

members = [
    "lib_a",
    "lib_b",
    "bin"
]
```

and my folder tree is
```
.
├── Cargo.lock
├── Cargo.toml
├── lib_a/
│   ├── Cargo.toml
│   └── src/
│   └── tests/
├── lib_b/
│   ├── Cargo.toml
│   ├── src/
│   └── tests/
├── bin/
│   ├── Cargo.toml
│   ├── src/
│   └── tests/
└── target/
```

and I get `manifest path '/github/workspace/Cargo.toml' is a virtual manifest, but this command requires running against an actual package in this workspace`

should I just change the `SRC_DIR` environment? or has others way

**Comment by Douile** [comment]
Just change SRC_DIR

**Comment by sakurayang** [comment]
Okay, but is it means I must modify the `ci.yml` to add a new item to `matrix` every time I add a new crate to the workspace?
or there is another way to do it without modifying the `ci.yml` every time?

**Comment by stackinspector** [comment]
> Just change SRC_DIR

But what can I do if there are multiple bin crates to build?

**Comment by Douile** [comment]
In future we could add support for the `-p` argument which allows you to specify multiple packages in one build command.
```shell
$ cargo build -p work1 -p work2
```
For now a workaround would be adding `SRC_DIR` to your build matrix e.g.
```yml

on:
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-pc-windows-gnu, x86_64-unknown-linux-musl]
        package: [work1, work2]
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUSTTARGET: ${{ matrix.target }}
          SRC_DIR: ${{ matrix.package }}
          EXTRA_FILES: "README.md LICENSE"
```
