### ISSUE TITLE
run successfully but no binary shows in the github release pages

### ISSUE THREAD

**Issue by rmGFW** [rust-build/rust-build.action#48]
this is my config , it goes well ,  but no binary upload to release pages
```yaml
on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          [
            x86_64-pc-windows-gnu,
            x86_64-unknown-linux-musl,
            x86_64-apple-darwin,
          ]
    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive
          token: ${{ secrets.MY_REPO_PAT }}
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}

````
