### ISSUE TITLE
rust-build.test sets MINIFY to "yes" while only true/false seem to be supported

### ISSUE THREAD

**Issue by localghost** [rust-build/rust-build.action#83]
In `https://github.com/rust-build/rust-build.test/blob/master/.github/workflows/build.yml`:
```

jobs:
  release:
    ...
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@master
        ...
        with:
          ...
          MINIFY: "yes"
```
which is misleading.
