### ISSUE TITLE
Windows Defender detects Trojan in produced binary

### ISSUE THREAD

**Issue by jeroenpelgrims** [rust-build/rust-build.action#89]
![image](https://github.com/rust-build/rust-build.action/assets/149305/b3196cd3-d042-4e85-8373-60afb0a6b93f)

This is only detected in the binary that was added to the release by this build action.  
When I build the executable manually then no issue is detected.
The binary produced by the action is also slightly larger than the one built locally. (I don't know if I used the same rust version though, that could have an effect)

In case you want to see the source for what I'm trying to build:
https://github.com/jeroenpelgrims/ynab-belfius

**Comment by Douile** [comment]
This is very alarming, would it be possible to link a virus total scan of the binary?

**Comment by jeroenpelgrims** [comment]
This is the report for the Windows binary:
https://www.virustotal.com/gui/file/3f62f9add12714eac79cb46512ad39a355964868ffb2a53bc6eafe2f28bc8d7a?nocache=1
This is the one for the Linux binary (it's clean):
https://www.virustotal.com/gui/file/693f3f89837a2e360146b251d55ee782e80635d101cbc3d34121e66dbdb8dc6b?nocache=1

I've created a new release for this issue.
The original files can be looked at here: https://github.com/jeroenpelgrims/ynab-belfius/releases

**Comment by Douile** [comment]
After a lot of testing I have found that any rust program cross-compiled on alpine linux linked using mingw-w64 seems to get the same detection: https://www.virustotal.com/gui/file/25e247564dc98cb64f386c3b791108467dcd6a69f676fb9587f519c9c8eff197 (I'm not sure if they get detected by windows defender as I don't have windows).

Compiling using cross-rs there is a different detection but the binary is still detected as malicious.

I believe that this is a false positive because the toolchain I used to replicate the detection would require one of the following to be compromised:

- docker.io/alpine
- apkpkg/rustup
- apkpkg/mingw-w64-gcc
- mingw itself: https://stackoverflow.com/questions/62364507/compiled-c-executable-is-detected-as-a-virus-by-windows-defender
- rustup toolchains
- My system

If u want to avoid any detections this might be possible by using github actions' windows runner (I haven't tested this):

```yml
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo build --release
      - uses: diamondburned/action-upload-release@main
        with:
          files: target/release/my-program.exe
```

**Comment by jeroenpelgrims** [comment]
I had to split up the build and the add-to-release since `diamondburned/action-upload-release` doesn't seem to support running on Windows, the paths are messed up.

I build on Windows, and then add the binary to the release on a linux job.
```
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo build --release
      - uses: actions/upload-artifact@v4
        with:
          path: ./target/release
          if-no-files-found: error
          retention-days: 1
          overwrite: true

  add_to_release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: .
      - uses: diamondburned/action-upload-release@main
        with:
          files: artifact/ynab-belfius.exe
```

But unfortunately... Same result. Both Virustotal and Windows defender seem to detect threats :(

https://www.virustotal.com/gui/file/9da5ec8b4cbc750d338e563fb5810148565d174d021ce7f9eb0b6acef43f425b?nocache=1

![image](https://github.com/rust-build/rust-build.action/assets/149305/8d61a399-7364-4afb-a67a-85f43d65a7b4)
